name:                parallel-eval-test
version:             0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - deepseq
  - parallel
  - ghc-heap-view

executables:
  parallel-eval-test:
    source-dirs:      src
    main:             Main.hs
